# Generated by Django 5.1.3 on 2025-10-14 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0002_addsystemvariable_configurations_gsttaxmastersdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('path', models.TextField()),
                ('upload_date', models.TextField(blank=True, null=True)),
                ('okay_status', models.TextField(blank=True, null=True)),
                ('okay_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='waiting', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miroapp.companydetails')),
            ],
        ),
    ]
