# Generated by Django 5.1.3 on 2025-10-16 07:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0003_invoicedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemVariableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_var', models.CharField(max_length=50)),
                ('po_header', models.CharField(max_length=50)),
                ('miro_header', models.CharField(max_length=50)),
                ('se_header', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miroapp.companydetails')),
            ],
        ),
    ]
