# Generated by Django 5.1.3 on 2025-10-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miroapp", "0004_systemvariablemapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="opengrndata",
            name="inv_no",
            field=models.CharField(default="1", max_length=40),
            preserve_default=False,
        ),
    ]
