# Generated by Django 5.1.3 on 2025-10-24 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0005_opengrndata_inv_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='wholdtax_master_headers',
            field=models.JSONField(default=list, help_text='SAC master headers'),
        ),
        migrations.CreateModel(
            name='VendorsTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendor_code', models.CharField(blank=True, max_length=11, null=True)),
                ('inv_num', models.CharField(blank=True, max_length=20, null=True)),
                ('inv_date', models.CharField(blank=True, max_length=11, null=True)),
                ('inv_value', models.CharField(blank=True, max_length=11, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_invoice_total', to='miroapp.companydetails')),
            ],
        ),
    ]
