# Generated by Django 5.1.3 on 2025-10-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0006_header_wholdtax_master_headers_vendorstotals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorstotals',
            name='inv_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withholdingtaxmastersdata',
            name='wtaxcode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
