# Generated by Django 5.1.3 on 2025-10-28 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0007_alter_vendorstotals_inv_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('CompanyCode', models.CharField(max_length=10)),
                ('DocumentNumber', models.CharField(max_length=15)),
                ('DocType', models.CharField(max_length=5)),
                ('InvoiceDate', models.CharField(max_length=11)),
                ('PostingDate', models.CharField(max_length=11)),
                ('AP_Inv_doc_num', models.CharField(max_length=15)),
                ('Currency', models.CharField(max_length=5)),
                ('ExchangeRate', models.CharField(max_length=3)),
                ('VendorCode', models.CharField(max_length=15)),
                ('VendorName', models.CharField(max_length=100)),
                ('PaymentTerms', models.CharField(max_length=5)),
                ('BaselineDate', models.CharField(max_length=11)),
                ('PO_Number', models.CharField(max_length=15)),
                ('PO_Item', models.CharField(max_length=15)),
                ('GR_Number', models.CharField(max_length=15)),
                ('MaterialNo', models.CharField(max_length=15)),
                ('Qty_Invoiced', models.CharField(max_length=4)),
                ('UoM', models.CharField(max_length=4)),
                ('NetPrice', models.CharField(max_length=15)),
                ('InvoiceAmount', models.CharField(max_length=20)),
                ('TaxCode', models.CharField(max_length=5)),
                ('TaxAmount', models.CharField(max_length=15)),
                ('WithholdingTaxCode', models.CharField(max_length=5)),
                ('UnplannedDeliveryCost', models.CharField(max_length=15)),
                ('GLAccount', models.CharField(max_length=15)),
                ('CostCenter', models.CharField(max_length=10)),
                ('WBS_Element', models.CharField(max_length=50)),
                ('AssetNo', models.CharField(max_length=15)),
                ('PaymentBlock', models.CharField(max_length=5)),
                ('Narration', models.CharField(max_length=50)),
                ('MigoDocDate', models.CharField(max_length=11)),
                ('SuppInv_no', models.CharField(max_length=30)),
                ('item_descritption', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miroapp.companydetails')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceGroupKey', models.UUIDField(db_index=True)),
                ('VendorCode', models.CharField(blank=True, max_length=15, null=True)),
                ('VendorName', models.CharField(blank=True, max_length=100, null=True)),
                ('InvoiceNo', models.CharField(blank=True, max_length=30, null=True)),
                ('InvoiceDate', models.CharField(blank=True, max_length=11, null=True)),
                ('InvoiceValue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('InvoiceCheck', models.JSONField(default=dict)),
                ('Status', models.CharField(blank=True, default='Pending', max_length=20, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miroapp.companydetails')),
            ],
            options={
                'verbose_name_plural': 'Invoice Summaries',
                'ordering': ['-CreatedAt'],
            },
        ),
    ]
