# Generated by Django 5.1.3 on 2025-10-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0008_invoicedetails_invoicesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=100)),
                ('mapped_headers1', models.JSONField(default=dict)),
                ('mapped_headers2', models.JSONField(default=dict)),
                ('file_no', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
