# Generated by Django 5.1.3 on 2025-11-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0009_templatemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=100)),
                ('VendorGst', models.CharField(max_length=16)),
                ('VendorCode', models.CharField(max_length=16)),
                ('InvNo', models.CharField(max_length=16)),
                ('CustomerGst', models.CharField(max_length=16)),
                ('TotalAmount', models.CharField(max_length=16)),
                ('TotalTax', models.CharField(max_length=16)),
                ('BasicAmount', models.CharField(max_length=16)),
                ('TaxType', models.CharField(max_length=16)),
                ('file_path', models.CharField(max_length=16)),
                ('api_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoicesummary',
            name='unique_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
