# Generated by Django 5.1.3 on 2025-11-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0010_pendinginvoices_invoicesummary_unique_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesummary',
            name='path',
            field=models.TextField(default='D:\\VS CODE\\Miro App Updated\\project\\media\\invoices\\Blue Consulting Private Limited (nasim.blueconsulting@gmail.com)\x8251014_115550_ADGIFTS_INDIA_PRIVATE_LIMITED-1479-25-26'),
            preserve_default=False,
        ),
    ]
