# Generated by Django 5.1.3 on 2025-11-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0011_invoicesummary_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinginvoices',
            name='file_path',
        ),
        migrations.AddField(
            model_name='pendinginvoices',
            name='path',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendinginvoices',
            name='unique_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
