# Generated by Django 5.1.3 on 2025-11-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0012_remove_pendinginvoices_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesummary',
            name='InvoiceDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendinginvoices',
            name='TaxType',
            field=models.JSONField(default=dict),
        ),
    ]
