# Generated by Django 5.1.3 on 2025-11-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0013_alter_invoicesummary_invoicedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='unalloacatedcost_gl',
            field=models.JSONField(default=list, help_text='list of gl for unallocated cost'),
        ),
    ]
