# Generated by Django 5.1.3 on 2025-11-12 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miroapp", "0014_header_unalloacatedcost_gl"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_matrix", models.JSONField(default=dict)),
                ("radio_matrix", models.JSONField(default=dict)),
                ("unalloactedcost_matrix", models.JSONField(default=dict)),
                ("currency_matrix", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="miroapp.companydetails",
                    ),
                ),
            ],
        ),
    ]
