# Generated by Django 5.1.3 on 2025-11-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miroapp", "0015_rolematrix"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicesummary",
            name="Role",
            field=models.CharField(default="Processor", max_length=20),
        ),
    ]
