# Generated by Django 5.1.3 on 2025-11-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miroapp", "0016_invoicesummary_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicesummary",
            name="ExchangeRate",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="invoicesummary",
            name="Narration",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="invoicesummary",
            name="TaxCode",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="invoicesummary",
            name="WithholdingTaxCode",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
