# Generated by Django 5.1.3 on 2025-11-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "miroapp",
            "0017_invoicesummary_exchangerate_invoicesummary_narration_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicesummary",
            name="VendorGst",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="withholdingtaxmastersdata",
            name="wtaxsection",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
