# Generated by Django 5.1.3 on 2025-11-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miroapp", "0018_invoicesummary_vendorgst_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoicesummary",
            old_name="Role",
            new_name="Pending_with",
        ),
        migrations.AddField(
            model_name="invoicesummary",
            name="original_data",
            field=models.JSONField(default=dict),
        ),
    ]
