# Generated by Django 5.1.3 on 2025-11-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0019_rename_role_invoicesummary_pending_with_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolematrix',
            name='currency_matrix',
        ),
        migrations.RemoveField(
            model_name='rolematrix',
            name='unalloactedcost_matrix',
        ),
        migrations.AddField(
            model_name='rolematrix',
            name='field_matrix_change',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='rolematrix',
            name='radio_matrix_change',
            field=models.JSONField(default=list),
        ),
    ]
