# Generated by Django 5.1.3 on 2025-11-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0020_remove_rolematrix_currency_matrix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolematrix',
            name='field_matrix_change',
        ),
        migrations.RemoveField(
            model_name='rolematrix',
            name='radio_matrix_change',
        ),
        migrations.AddField(
            model_name='invoicesummary',
            name='field_matrix_change',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='invoicesummary',
            name='radio_matrix_change',
            field=models.JSONField(default=list),
        ),
    ]
