# Generated by Django 5.1.3 on 2025-11-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miroapp", "0021_remove_rolematrix_field_matrix_change_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicesummary",
            name="checker_approval",
            field=models.JSONField(default=dict),
        ),
    ]
