# Generated by Django 5.1.3 on 2025-11-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0022_invoicesummary_checker_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='gsttax_master_headers',
            field=models.JSONField(default=list, help_text='SAC master headers'),
        ),
    ]
