# Generated by Django 5.1.3 on 2025-11-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miroapp", "0023_header_gsttax_master_headers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sacmastersdata",
            old_name="glcode",
            new_name="rcm_fc",
        ),
        migrations.RenameField(
            model_name="sacmastersmapping",
            old_name="glcode",
            new_name="rcm_fc",
        ),
        migrations.AddField(
            model_name="header",
            name="hsn_master_headers",
            field=models.JSONField(default=list, help_text="HSN master headers"),
        ),
        migrations.AlterField(
            model_name="header",
            name="gsttax_master_headers",
            field=models.JSONField(default=list, help_text="GST master headers"),
        ),
        migrations.AlterField(
            model_name="hsnmastersmapping",
            name="block_input",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="hsnmastersmapping",
            name="cgstrate",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="hsnmastersmapping",
            name="hsncode",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="hsnmastersmapping",
            name="igstrate",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="hsnmastersmapping",
            name="sgstrate",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
