# Generated by Django 5.1.3 on 2025-11-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("miroapp", "0024_rename_glcode_sacmastersdata_rcm_fc_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sacmastersdata",
            old_name="cgstrate",
            new_name="taxrate",
        ),
        migrations.RenameField(
            model_name="sacmastersmapping",
            old_name="cgstrate",
            new_name="taxrate",
        ),
        migrations.RemoveField(
            model_name="sacmastersdata",
            name="igstrate",
        ),
        migrations.RemoveField(
            model_name="sacmastersdata",
            name="sgstrate",
        ),
        migrations.RemoveField(
            model_name="sacmastersmapping",
            name="igstrate",
        ),
        migrations.RemoveField(
            model_name="sacmastersmapping",
            name="sgstrate",
        ),
    ]
