# Generated by Django 5.1.3 on 2025-11-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miroapp", "0025_rename_cgstrate_sacmastersdata_taxrate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sacmastersdata",
            name="section",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
