# Generated by Django 5.1.3 on 2025-11-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miroapp", "0026_sacmastersdata_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendinginvoices",
            name="InvDate",
            field=models.CharField(default="VIJAYA METAL FINISHERS", max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pendinginvoices",
            name="VendorName",
            field=models.CharField(default="2025-08-11", max_length=50),
            preserve_default=False,
        ),
    ]
