# Generated by Django 5.1.3 on 2025-11-22 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miroapp", "0027_pendinginvoices_invdate_pendinginvoices_vendorname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendinginvoices",
            name="company_code",
        ),
        migrations.AddField(
            model_name="pendinginvoices",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="miroapp.companydetails",
            ),
            preserve_default=False,
        ),
    ]
