# Generated by Django 5.1.3 on 2025-11-26 09:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0028_remove_pendinginvoices_company_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='system_var',
            field=models.JSONField(default=list, help_text='List of system variables'),
        ),
        migrations.CreateModel(
            name='AdditionalSystemVariableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_var', models.CharField(max_length=50)),
                ('system_var_user_name', models.CharField(max_length=50)),
                ('po_header', models.CharField(max_length=50)),
                ('miro_header', models.CharField(max_length=50)),
                ('se_header', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miroapp.companydetails')),
            ],
        ),
        migrations.CreateModel(
            name='MissingDataInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VendorGst', models.CharField(max_length=16)),
                ('VendorCode', models.CharField(max_length=16)),
                ('InvNo', models.CharField(max_length=16)),
                ('InvDate', models.CharField(max_length=16)),
                ('VendorName', models.CharField(max_length=50)),
                ('CustomerGst', models.CharField(max_length=16)),
                ('TotalAmount', models.CharField(max_length=16)),
                ('TotalTax', models.CharField(max_length=16)),
                ('BasicAmount', models.CharField(max_length=16)),
                ('TaxType', models.JSONField(default=dict)),
                ('path', models.TextField()),
                ('unique_name', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=150, null=True)),
                ('api_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miroapp.companydetails')),
            ],
        ),
    ]
