# Generated by Django 5.1.3 on 2025-12-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0029_alter_header_system_var_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurations',
            name='matching_logic_ratio',
            field=models.JSONField(default=dict),
        ),
    ]
