# Generated by Django 5.1.3 on 2025-12-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0030_configurations_matching_logic_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemvariablemapping',
            name='secondary_source',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
