# Generated by Django 5.1.3 on 2025-12-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0031_systemvariablemapping_secondary_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurations',
            name='data_upload_rights',
            field=models.JSONField(default=dict),
        ),
    ]
