# Generated by Django 5.1.3 on 2025-12-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0032_configurations_data_upload_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesummary',
            name='payment_indicator',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
