# Generated by Django 5.1.3 on 2025-12-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0033_invoicesummary_payment_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesummary',
            name='withholdtax',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
