# Generated by Django 5.1.3 on 2025-12-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miroapp", "0034_invoicesummary_withholdtax"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicedetails",
            name="item_rate",
            field=models.CharField(default="50", max_length=30),
            preserve_default=False,
        ),
    ]
