# Generated by Django 5.1.3 on 2025-12-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0035_invoicedetails_item_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingdatainvoices',
            name='InvoiceGroupKey',
            field=models.UUIDField(db_index=True, default='bc0d2c29aeb24f99815b2bc7e070134b'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendinginvoices',
            name='InvoiceGroupKey',
            field=models.UUIDField(db_index=True, default='bc0d2c29aeb24f99815b2bc7e070134b'),
            preserve_default=False,
        ),
    ]
