# Generated by Django 5.1.3 on 2025-12-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miroapp", "0036_missingdatainvoices_invoicegroupkey_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendinginvoices",
            name="InvNo",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="pendinginvoices",
            name="VendorCode",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
