# Generated by Django 5.1.3 on 2025-12-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0038_alter_missingdatainvoices_invno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesummary',
            name='Currency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='invoicesummary',
            name='account_indicator',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesummary',
            name='payment_indicator',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesummary',
            name='withholdtax',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
