# Generated by Django 5.1.3 on 2025-12-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0039_invoicesummary_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesummary',
            name='InvCurrency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
