# Generated by Django 5.1.3 on 2025-12-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miroapp", "0040_invoicesummary_invcurrency"),
    ]

    operations = [
        migrations.AddField(
            model_name="missingdatainvoices",
            name="checker_approval",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="missingdatainvoices",
            name="checker_approval_req",
            field=models.CharField(default="No", max_length=4),
        ),
        migrations.AddField(
            model_name="missingdatainvoices",
            name="status",
            field=models.CharField(default="Pending", max_length=16),
        ),
    ]
