# Generated by Django 5.1.3 on 2025-12-22 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miroapp", "0041_missingdatainvoices_checker_approval_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GLCodes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gl_code", models.CharField(max_length=16)),
                ("code_description", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="miroapp.companydetails",
                    ),
                ),
            ],
        ),
    ]
