# Generated by Django 5.1.3 on 2025-12-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0042_glcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingdatainvoices',
            name='InvoiceCheck',
            field=models.JSONField(default=dict),
        ),
    ]
