# Generated by Django 5.1.3 on 2025-12-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miroapp", "0043_missingdatainvoices_invoicecheck"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicesummary",
            name="InvoiceValueMigo",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoicedetails",
            name="AP_Inv_doc_num",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="invoicesummary",
            name="ExchangeRate",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="invoicesummary",
            name="InvoiceNo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="invoicesummary",
            name="InvoiceValue",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
