# Generated by Django 5.1.3 on 2025-12-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miroapp", "0044_invoicesummary_invoicevaluemigo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicesummary",
            name="unplanned_cost",
            field=models.JSONField(default=dict),
        ),
    ]
