# Generated by Django 5.1.3 on 2025-12-29 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0045_invoicesummary_unplanned_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckerApprovalsInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceGroupKey', models.UUIDField(db_index=True)),
                ('path', models.TextField()),
                ('unique_name', models.CharField(blank=True, max_length=100, null=True)),
                ('api_response', models.JSONField(default=dict)),
                ('message', models.CharField(blank=True, max_length=150, null=True)),
                ('exception_type', models.CharField(blank=True, max_length=30, null=True)),
                ('exception_data', models.JSONField(default=dict)),
                ('status', models.CharField(default='Pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miroapp.companydetails')),
            ],
        ),
    ]
