# Generated by Django 5.1.3 on 2025-12-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0046_checkerapprovalsinvoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkerapprovalsinvoices',
            name='InvoiceNo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='checkerapprovalsinvoices',
            name='VendorCode',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='checkerapprovalsinvoices',
            name='VendorName',
            field=models.CharField(default='ABC', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missingdatainvoices',
            name='InvNo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
