# Generated by Django 5.1.3 on 2025-12-29 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0047_checkerapprovalsinvoices_invoiceno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkerapprovalsinvoices',
            name='InvoiceId',
            field=models.PositiveIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='InvoiceId',
            field=models.PositiveIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicesummary',
            name='InvoiceId',
            field=models.PositiveIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missingdatainvoices',
            name='InvoiceId',
            field=models.PositiveIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendinginvoices',
            name='InvoiceId',
            field=models.PositiveIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InvoiceId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('unique_name', models.CharField(blank=True, max_length=100, null=True)),
                ('VendorName', models.CharField(blank=True, max_length=100, null=True)),
                ('InvoiceNo', models.CharField(blank=True, max_length=50, null=True)),
                ('InvoiceDate', models.DateField(blank=True, null=True)),
                ('VendorGst', models.CharField(blank=True, max_length=15, null=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miroapp.companydetails')),
            ],
        ),
    ]
