# Generated by Django 5.1.3 on 2025-12-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miroapp", "0048_checkerapprovalsinvoices_invoiceid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="podata",
            name="inv_no",
            field=models.CharField(default="abc", max_length=40),
            preserve_default=False,
        ),
    ]
