# Generated by Django 5.1.3 on 2025-12-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0049_podata_inv_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorstotals',
            name='inv_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
