# Generated by Django 5.1.3 on 2026-01-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0050_alter_vendorstotals_inv_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurations',
            name='pans',
            field=models.JSONField(default=list),
        ),
    ]
