# Generated by Django 5.1.3 on 2026-01-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miroapp', '0051_configurations_pans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurations',
            name='pans',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
